FROM python:3.8-buster
ENV PYTHONUNBUFFERED 1

# Update aptitude
RUN apt-get update

# Install software
RUN apt-get install -y git

ENV POETRY_HOME="/opt/poetry"
ENV PATH="$POETRY_HOME/bin:$PATH"
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

# Clone the challenge API code into the docker container
RUN git clone https://github.com/datamindedsolutions/noteworth-challenge-api.git
RUN echo $(ls)
WORKDIR /noteworth-challenge-api
RUN poetry install
